# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Enter a Valid 10 digit number', regex='^.{10}$')])),
                ('enroll', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Enter a Valid 11 digit Enrollment number', regex='^.{11}$')])),
                ('group', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=8)),
            ],
        ),
    ]
