# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='enroll',
            field=models.CharField(max_length=11),
        ),
    ]
